### ISSUE TITLE
java.io.IOException: invalid constant type: 15

### ISSUE THREAD

**Issue by kevinke2012** [allwefantasy/ServiceFramework#47]
我在进行quickstart的时候，提示这个错误，怎么解决呢，
java.lang.RuntimeException: java.io.IOException: invalid constant type: 15
	at javassist.CtClassType.getClassFile2(CtClassType.java:204)
	at javassist.CtClassType.subtypeOf(CtClassType.java:304)
	at javassist.CtClassType.subtypeOf(CtClassType.java:319)
	at javassist.compiler.MemberResolver.compareSignature(MemberResolver.java:248)
	at javassist.compiler.MemberResolver.lookupMethod(MemberResolver.java:120)
	at javassist.compiler.MemberResolver.lookupMethod(MemberResolver.java:97)
	at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:711)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:688)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.compileExpr(CodeGen.java:229)
	at javassist.compiler.CodeGen.atReturnStmnt2(CodeGen.java:598)
	at javassist.compiler.JvstCodeGen.atReturnStmnt(JvstCodeGen.java:425)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:363)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atMethodBody(CodeGen.java:292)
	at javassist.compiler.CodeGen.atMethodDecl(CodeGen.java:274)
	at javassist.compiler.ast.MethodDecl.accept(MethodDecl.java:44)
	at javassist.compiler.Javac.compileMethod(Javac.java:169)
	at javassist.compiler.Javac.compile(Javac.java:95)
	at javassist.CtNewMethod.make(CtNewMethod.java:74)
	at javassist.CtNewMethod.make(CtNewMethod.java:45)
	at javassist.CtMethod.make(CtMethod.java:130)
	at net.csdn.jpa.enhancer.ClassMethodEnhancer.enhanceModelMethods(ClassMethodEnhancer.java:97)
	at net.csdn.jpa.enhancer.ClassMethodEnhancer.enhance(ClassMethodEnhancer.java:37)
	at net.csdn.jpa.enhancer.JPAEnhancer.enhanceThisClass2(JPAEnhancer.java:85)
	at net.csdn.jpa.JPA$JPAModelLoader.load(JPA.java:350)
	at net.csdn.jpa.JPA.loadModels(JPA.java:208)
	at net.csdn.jpa.JPA.configure(JPA.java:76)
	at net.csdn.bootstrap.Bootstrap.configureSystem(Bootstrap.java:82)
	at net.csdn.bootstrap.Bootstrap.main(Bootstrap.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.csdn.bootstrap.Application.main(Application.java:18)
	at com.example.Example.main(Example.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.io.IOException: invalid constant type: 15
	at javassist.bytecode.ConstPool.readOne(ConstPool.java:1113)
	at javassist.bytecode.ConstPool.read(ConstPool.java:1056)
	at javassist.bytecode.ConstPool.<init>(ConstPool.java:150)
	at javassist.bytecode.ClassFile.read(ClassFile.java:765)
	at javassist.bytecode.ClassFile.<init>(ClassFile.java:109)
	at javassist.CtClassType.getClassFile2(CtClassType.java:191)
	... 44 more

**Comment by kevinke2012** [comment]
已经解决啦，因为我用的是jdk8 把javassist 更新到3.19.0-GA就可以了

**Comment by allwefantasy** [comment]
棒棒哒

**Comment by jpgtama** [comment]
这个解决了我的问题。多谢。
