### ISSUE TITLE
Example报错

### ISSUE THREAD

**Issue by flydish2017** [allwefantasy/ServiceFramework#54]
application.yml配置为：
mysql:
disable: false

idea运行Example.java报以下错误：

D:\home\opt\jdk1.8.0_40\bin\java "-javaagent:D:\home\opt\IntelliJ IDEA 2017.1.4\lib\idea_rt.jar=53584:D:\home\opt\IntelliJ IDEA 2017.1.4\bin" -Dfile.encoding=UTF-8 -classpath D:\home\opt\jdk1.8.0_40\jre\lib\charsets.jar;D:\home\opt\jdk1.8.0_40\jre\lib\deploy.jar;D:\home\opt\jdk1.8.0_40\jre\lib\ext\access-bridge-64.jar;D:\home\opt\jdk1.8.0_40\jre\lib\ext\cldrdata.jar;D:\home\opt\jdk1.8.0_40\jre\lib\ext\dnsns.jar;D:\home\opt\jdk1.8.0_40\jre\lib\ext\jaccess.jar;D:\home\opt\jdk1.8.0_40\jre\lib\ext\jfxrt.jar;D:\home\opt\jdk1.8.0_40\jre\lib\ext\localedata.jar;D:\home\opt\jdk1.8.0_40\jre\lib\ext\nashorn.jar;D:\home\opt\jdk1.8.0_40\jre\lib\ext\sunec.jar;D:\home\opt\jdk1.8.0_40\jre\lib\ext\sunjce_provider.jar;D:\home\opt\jdk1.8.0_40\jre\lib\ext\sunmscapi.jar;D:\home\opt\jdk1.8.0_40\jre\lib\ext\sunpkcs11.jar;D:\home\opt\jdk1.8.0_40\jre\lib\ext\zipfs.jar;D:\home\opt\jdk1.8.0_40\jre\lib\javaws.jar;D:\home\opt\jdk1.8.0_40\jre\lib\jce.jar;D:\home\opt\jdk1.8.0_40\jre\lib\jfr.jar;D:\home\opt\jdk1.8.0_40\jre\lib\jfxswt.jar;D:\home\opt\jdk1.8.0_40\jre\lib\jsse.jar;D:\home\opt\jdk1.8.0_40\jre\lib\management-agent.jar;D:\home\opt\jdk1.8.0_40\jre\lib\plugin.jar;D:\home\opt\jdk1.8.0_40\jre\lib\resources.jar;D:\home\opt\jdk1.8.0_40\jre\lib\rt.jar;D:\study\Transformer\ServiceFramework-master\serviceframework-web\target\classes;D:\study\Transformer\ServiceFramework-master\serviceframework-common\target\classes;D:\java\repository\joda-time\joda-time\2.3\joda-time-2.3.jar;D:\java\repository\org\yaml\snakeyaml\1.9\snakeyaml-1.9.jar;D:\java\repository\net\sf\json-lib\json-lib\2.4\json-lib-2.4-jdk15.jar;D:\java\repository\commons-beanutils\commons-beanutils\1.8.0\commons-beanutils-1.8.0.jar;D:\java\repository\net\sf\ezmorph\ezmorph\1.0.6\ezmorph-1.0.6.jar;D:\java\repository\jline\jline\0.9.94\jline-0.9.94.jar;D:\java\repository\javassist\javassist\3.12.1.GA\javassist-3.12.1.GA.jar;D:\java\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;D:\java\repository\org\slf4j\slf4j-api\1.6.1\slf4j-api-1.6.1.jar;D:\java\repository\org\slf4j\jcl-over-slf4j\1.6.1\jcl-over-slf4j-1.6.1.jar;D:\java\repository\org\slf4j\slf4j-log4j12\1.6.1\slf4j-log4j12-1.6.1.jar;D:\java\repository\com\google\guava\guava\15.0\guava-15.0.jar;D:\java\repository\com\google\inject\guice\3.0\guice-3.0.jar;D:\java\repository\javax\inject\javax.inject\1\javax.inject-1.jar;D:\java\repository\aopalliance\aopalliance\1.0\aopalliance-1.0.jar;D:\java\repository\com\google\inject\extensions\guice-assistedinject\3.0\guice-assistedinject-3.0.jar;D:\java\repository\com\google\inject\extensions\guice-multibindings\3.0\guice-multibindings-3.0.jar;D:\java\repository\com\mycila\com\google\inject\guice\3.0-20100927\guice-3.0-20100927.jar;D:\java\repository\mysql\mysql-connector-java\5.1.6\mysql-connector-java-5.1.6.jar;D:\java\repository\javax\servlet\javax.servlet-api\3.1.0\javax.servlet-api-3.1.0.jar;D:\study\Transformer\ServiceFramework-master\serviceframework-jetty-9-server\target\classes;D:\java\repository\org\eclipse\jetty\jetty-server\9.2.16.v20160414\jetty-server-9.2.16.v20160414.jar;D:\java\repository\org\eclipse\jetty\jetty-continuation\9.2.16.v20160414\jetty-continuation-9.2.16.v20160414.jar;D:\java\repository\org\eclipse\jetty\jetty-io\9.2.16.v20160414\jetty-io-9.2.16.v20160414.jar;D:\java\repository\org\eclipse\jetty\jetty-http\9.2.16.v20160414\jetty-http-9.2.16.v20160414.jar;D:\java\repository\org\eclipse\jetty\jetty-util\9.2.16.v20160414\jetty-util-9.2.16.v20160414.jar;D:\java\repository\org\eclipse\jetty\jetty-servlet\9.2.16.v20160414\jetty-servlet-9.2.16.v20160414.jar;D:\java\repository\org\eclipse\jetty\jetty-security\9.2.16.v20160414\jetty-security-9.2.16.v20160414.jar;D:\java\repository\org\apache\httpcomponents\httpclient\4.2.5\httpclient-4.2.5.jar;D:\java\repository\org\apache\httpcomponents\httpcore\4.2.4\httpcore-4.2.4.jar;D:\java\repository\commons-logging\commons-logging\1.1.1\commons-logging-1.1.1.jar;D:\java\repository\commons-codec\commons-codec\1.6\commons-codec-1.6.jar;D:\java\repository\org\apache\velocity\velocity\1.7\velocity-1.7.jar;D:\java\repository\commons-collections\commons-collections\3.2.1\commons-collections-3.2.1.jar;D:\java\repository\commons-lang\commons-lang\2.4\commons-lang-2.4.jar;D:\java\repository\junit\junit\4.11\junit-4.11.jar;D:\java\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;D:\java\repository\org\scala-lang\scala-library\2.11.8\scala-library-2.11.8.jar;D:\java\repository\org\scala-lang\jline\2.11.0-M3\jline-2.11.0-M3.jar;D:\java\repository\org\fusesource\jansi\jansi\1.4\jansi-1.4.jar;D:\java\repository\com\alibaba\dubbo\2.5.3\dubbo-2.5.3.jar;D:\java\repository\org\springframework\spring\2.5.6.SEC03\spring-2.5.6.SEC03.jar;D:\java\repository\org\javassist\javassist\3.15.0-GA\javassist-3.15.0-GA.jar;D:\java\repository\org\jboss\netty\netty\3.2.5.Final\netty-3.2.5.Final.jar com.example.Example
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.csdn.bootstrap.Application.main(Application.java:18)
	at com.example.Example.main(Example.java:12)
Caused by: java.lang.NoClassDefFoundError: net/csdn/jpa/JPA$CSDNORMConfiguration
	at net.csdn.bootstrap.Bootstrap.configureSystem(Bootstrap.java:82)
	at net.csdn.bootstrap.Bootstrap.main(Bootstrap.java:41)
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.csdn.jpa.JPA$CSDNORMConfiguration
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more

Process finished with exit code 0

**Comment by allwefantasy** [comment]
首先记得拉最新代码；其次你可能运行的是production模式，所以你可以将development复制一份为production即可。另外最新代码里，orm只是其中的一个模块，你运行的时候，理论上也会自动编译的。
